apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: daemonset-primeiro
  namespace: default
spec:
  template:
    metadata:
      labels:
        system: Strigus
    spec:
      containers:
      - image: nginx:1.7.9
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
  updateStrategy:
    type: RollingUpdate  
