apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pessoas-api
  name: pessoas-api
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pessoas-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pessoas-api
    spec:
      containers:
      - image: rogeriotadim/pessoas-api
        imagePullPolicy: Always
        name: pessoas-api
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 128Mi
            cpu: "100m"
          requests:
            memory: 64Mi
            cpu: "75m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
