apiVersion: v1
kind: LimitRange
metadata:
  name: limitando-recursos
spec:
  limits:
  - default:
      cpu: "750m"
      memory: 256Mi
    defaultRequest:
      cpu: "250m"
      memory: 64Mi
    type: Container

