ENV["HTTP_PROXY"] = "http://127.0.0.1:3128"
ENV["HTTPS_PROXY"] = "http://127.0.0.1:3128"
Vagrant.configure("2") do |config|
    ### config.vm.box = "bento/ubuntu-16.04"
    config.vm.box = "generic/debian9"
    config.vm.network "forwarded_port", guest: 80, host: 8086
    config.vm.synced_folder ".", "/vagrant"
    ####### Provision #######
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "provision/playbook.yml"
      ansible.verbose = true
    end
  end