version: '3.7'

services:

  web:
    image: nginx
    deploy:
      placement:
        constraints:
          - node.labels.dc == BR
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
      restart_policy: 
        condition: on-failure
    ports:
      - 80:80
    networks:
      - webserver

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - '8888:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.3'
          memory: 250M
    networks:
      - webserver

networks:
  webserver:
