apiVersion: v1
kind: LimitRange
metadata:
  name: limitando-recursos
spec:
  limits:
  - default:
      cpu: "750m"
      memory: 2048Mi
    defaultRequest:
      cpu: "250m"
      memory: 1024Mi
    type: Container

