apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: simple-api
  name: simple-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: simple-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: simple-api
    spec:
      containers:
      - image: rogeriotadim/simple-node-api:1.0.0
        env:
        - name: "PORT"
          value: "8080"

        name: simple-api
        ports:
        - containerPort: 8080
          name: "porta-api"
        resources:
          requests:
            cpu: "10m"
            memory: "32M"
          limits:
            cpu: "20m"
            memory: "64M"
