apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: simple-api
  name: simple-api
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: porta-api
  selector:
    run: simple-api
  type: NodePort
status:
  loadBalancer: {}
